image: node:22

pipelines:
  default:
    - parallel:
        - step:
            name: Lint Check
            caches:
              - node
            script:
              - npm install
              - npm run lint

        - step:
            name: React Build
            caches:
              - node
            script:
              - npm install
              - npm run build
            artifacts:
              - dist/**

    - step:
        name: Docker Build & Push (CD)
        services:
          - docker
        script:
          - docker build -t $DOCKER_USERNAME/frontend-app:latest .

          - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

          - docker push $DOCKER_USERNAME/frontend-app:latest

  pull-requests:
    '**':
      - step:
          name: PR Validation
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run build

definitions:
  services:
    docker:
      memory: 2048
