image: node:22

pipelines:
  branches:
    main:
      - parallel:
          - step:
              name: Lint Check
              caches:
                - node
              script:
                - npm install
                - npm run lint

          - step:
              name: React Build
              caches:
                - node
              script:
                - npm install
                - npm run build
              artifacts:
                - dist/**

      - step:
          name: Docker Build & Push
          services:
            - docker
          script:
            - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            - docker build -t $DOCKER_USERNAME/frontend-app:latest .
            - docker push $DOCKER_USERNAME/frontend-app:latest

      - step:
          name: Deploy to GCP VM
          script:
            - apt-get update && apt-get install -y openssh-client
            - echo "$SSH_PRIVATE_KEY_B64" | base64 -d > /tmp/id_rsa
            - chmod 600 /tmp/id_rsa
            - ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no shivam_u@34.29.30.10 '
                docker pull upshivam786/frontend-app:latest &&
                docker stop frontend-app || true &&
                docker rm frontend-app || true &&
                docker run -d -p 8080:80 --restart always --name frontend-app upshivam786/frontend-app:latest
              '

  pull-requests:
    '**':
      - step:
          name: PR Validation
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm run build

definitions:
  services:
    docker:
      memory: 2048
